### ISSUE TITLE
is this include disable dGPU?

### ISSUE THREAD

**Issue by zendzo** [dreadkopp/8470p_10.13.x#4]
hi I plan to use this boot file.
is your laptop has dgpu?
if it is use dgpu how you manage to disabled?

**Comment by dreadkopp** [comment]
Hi.

This was create from my HP which hasnt got a dedicated gpu. Check the BIOS
if you need to disable it. Might be possible to Patch out via custom dsdt
as well.

Also keep in mind that this hasnt been updated for some time now since I
don't own the machine any more

M. Z Mustofa <notifications@github.com> schrieb am Do., 21. Jan. 2021,
03:41:

**Comment by zendzo** [comment]
Hi,

thanks for your response.
I don't have bios setting on my laptop to disable dGPU.

I wish I can install at least Catalina on my Elitbook 8470p.
but I only got 3mb display with AMD Radon 7570m.
